In [1]:
a1 = [11,22,33,44,55]
print(a1)
print(type(a1))

[11, 22, 33, 44, 55]
<class 'list'>


In [2]:
import numpy as np

In [3]:
arr1  = np.array(a1)
print(arr1)

[11 22 33 44 55]


In [5]:
n = 125
x = str(n)
print(x)
print(type(x))

125
<class 'str'>


In [6]:
print(type(arr1))

<class 'numpy.ndarray'>


 ELEMENTWISE OPERATION

In [7]:
for i in a1:
    print(i*2)

22
44
66
88
110


In [8]:
a2 = [i*2 for i in a1]
print(a2)

[22, 44, 66, 88, 110]


In [11]:
arr1 * 3

array([ 33,  66,  99, 132, 165])

In [12]:
arr1 ** 2

array([ 121,  484, 1089, 1936, 3025], dtype=int32)

In [13]:
arr1 * arr1

array([ 121,  484, 1089, 1936, 3025])

In [14]:
arr1 + arr1

array([ 22,  44,  66,  88, 110])

In [15]:
arr1 * arr1 * arr1

array([  1331,  10648,  35937,  85184, 166375])

In [16]:
arr1

array([11, 22, 33, 44, 55])

In [22]:
arr2 = np.array([1,2,3])