In [2]:
import numpy as np

In [3]:
a1 = list(range(50))

In [4]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


In [5]:
%timeit [i*i for i in a1]

2.47 µs ± 48.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
a2 = np.arange(1000)

In [8]:
%timeit (a2*a2)

1.43 µs ± 16.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Array Attribute

In [9]:
a3 = [10,20,30,40]

In [10]:
a4 = np.array(a3)

In [11]:
a4

array([10, 20, 30, 40])

In [12]:
a4.shape

(4,)

In [13]:
a4.ndim

1

In [14]:
a4.size

4

## 1D Array Creation


In [3]:
a5 = [0,1,2,3,4,5,6,7,8,9]
print(type(a5))


a6 = list(range(25))
print(a6)

arr1 = np.array(a6)
print(arr1)

<class 'list'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


NameError: name 'np' is not defined

In [4]:
arr1.ndim

NameError: name 'arr1' is not defined

In [5]:
import numpy as np

In [6]:
a5 = [0,1,2,3,4,5,67,8,9]
print(type(a5))
a6 = list(range(25))
print((a6))

arr1 = np.array(a6)
print(arr1)

<class 'list'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [7]:
arr1.ndim

1

In [8]:
arr1.size

25

In [10]:
arr1.shape

(25,)

In [11]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr2.ndim

1

In [13]:
arr2.size

10

In [14]:
arr2.shape

(10,)

In [15]:
a7 = list(range(7,85,3))
arr7 = np.array(a7)
arr7.size

26

In [16]:
arr8 = np.linspace(1,10,5)
arr8

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
arr8 = np.arange(1,10,5)
arr8

array([1, 6])

In [18]:
arr8 = np.linspace(1,2,50)
arr8

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [19]:
arr8 = np.linspace(1,-2,50)
arr8

array([ 1.        ,  0.93877551,  0.87755102,  0.81632653,  0.75510204,
        0.69387755,  0.63265306,  0.57142857,  0.51020408,  0.44897959,
        0.3877551 ,  0.32653061,  0.26530612,  0.20408163,  0.14285714,
        0.08163265,  0.02040816, -0.04081633, -0.10204082, -0.16326531,
       -0.2244898 , -0.28571429, -0.34693878, -0.40816327, -0.46938776,
       -0.53061224, -0.59183673, -0.65306122, -0.71428571, -0.7755102 ,
       -0.83673469, -0.89795918, -0.95918367, -1.02040816, -1.08163265,
       -1.14285714, -1.20408163, -1.26530612, -1.32653061, -1.3877551 ,
       -1.44897959, -1.51020408, -1.57142857, -1.63265306, -1.69387755,
       -1.75510204, -1.81632653, -1.87755102, -1.93877551, -2.        ])