# 2D Array

In [18]:
m = [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]

In [17]:
print(type(m))

<class 'list'>


In [16]:
m

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]]

In [19]:
import numpy as np

In [20]:
m_arr = np.array(m)

In [21]:
m_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [24]:
np.ndarray

numpy.ndarray

In [25]:
type(m_arr)

numpy.ndarray

In [27]:
m_arr.shape

(2, 12)

In [29]:
m_arr.size

24

In [30]:
z = [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]


In [31]:
arr4 = np.array(z)

In [32]:
arr4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [33]:
arr4.shape

(3, 12)

In [34]:
arr4.size

36

In [36]:
arr5 = np.arange(12)

In [37]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
arr5.ndim

1

In [43]:
arr5.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [45]:
arr5.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [46]:
arr5.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [47]:
arr5.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [ ]:
#using linspace


In [52]:
arr6 = np.linspace(1,10,15).reshape(3,5)
arr6

array([[ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857],
       [ 4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429],
       [ 7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ]])

In [53]:
arr6.ndim

2

In [55]:
arr6.shape

(3, 5)

In [56]:
arr6.size

15