In [1]:
import numpy as np

In [6]:
arr1 = np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
arr1 + 10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [8]:
arr1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [9]:

arr1 % 2 == 0


array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [10]:
arr1[(arr1 % 2==0)&(arr1 % 3==0)]

array([0, 6])

# UNiversal Function



In [11]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,5])
print(a)
print(b)

[11 22 33 44 55]
[1 2 3 4 5]


In [12]:
 a + 10

array([21, 32, 43, 54, 65])

In [13]:
 a + b 

array([12, 24, 36, 48, 60])

In [14]:
a * b

array([ 11,  44,  99, 176, 275])

In [15]:
a/b

array([11., 11., 11., 11., 11.])

In [16]:

a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,0])
print(a)
print(b)

[11 22 33 44 55]
[1 2 3 4 0]


In [18]:
b/a

array([0.09090909, 0.09090909, 0.09090909, 0.09090909, 0.        ])

In [22]:
s = np.array([['Priya', 'Rohit', 'Aryan'],
       ['Neha', 'Avni', 'Akash'],
       ['Arjun', 'Riya', 'Devanshi']])
score = np.random.randint(10,100,15).reshape(5,3)

In [23]:
s[0]

array(['Priya', 'Rohit', 'Aryan'], dtype='<U8')

In [24]:
score

array([[72, 93, 80],
       [72, 93, 68],
       [93, 52, 20],
       [43, 52, 55],
       [34, 43, 68]])

In [25]:
score[score>50]

array([72, 93, 80, 72, 93, 68, 93, 52, 52, 55, 68])

In [27]:
score

array([[72, 93, 80],
       [72, 93, 68],
       [93, 52, 20],
       [43, 52, 55],
       [34, 43, 68]])

In [30]:
np.random.randint(10,100,15).reshape(5,3)

array([[79, 63, 31],
       [37, 40, 89],
       [28, 25, 70],
       [38, 90, 57],
       [65, 80, 20]])

SyntaxError: invalid syntax (<ipython-input-31-3d6cfb4a5e4d>, line 1)