In [1]:
import numpy as np

In [2]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,5])
print(a)
print(b)

[11 22 33 44 55]
[1 2 3 4 5]


In [3]:
a + b

array([12, 24, 36, 48, 60])

In [4]:
a * b

array([ 11,  44,  99, 176, 275])

In [5]:
np.sum(a)

165

In [6]:
np.min(a)

11

In [7]:
np.min(b)

1

In [8]:
np.max(a)

55

In [9]:
np.mean(b)

3.0

In [10]:
len(np.arange(10,60,2))

25

In [11]:
arr1 = np.arange(10,60,2).reshape(5,5)

In [12]:
arr1

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [13]:
np.sum(arr1,axis=None)

850

In [15]:
np.sum(arr1,axis=1)

array([ 70, 120, 170, 220, 270])

In [16]:
np.max(arr1,axis=0)

array([50, 52, 54, 56, 58])

In [17]:
np.mean(arr1,axis=1)

array([14., 24., 34., 44., 54.])

In [22]:
score = np.random.randint(10,100,15).reshape(3,5)

In [23]:
score

array([[53, 45, 34, 43, 55],
       [74, 56, 11, 59, 13],
       [89, 13, 32, 72, 93]])

In [24]:
np.sum(score,axis=0)

array([216, 114,  77, 174, 161])

In [25]:
np.mean(score,axis=1)

array([46. , 42.6, 59.8])

In [26]:
np.min(score,axis=1)

array([34, 11, 13])

In [27]:
np.max(score,axis=0)

array([89, 56, 34, 72, 93])

# Logical Function

In [28]:
score = np.random.randint(10,100,15).reshape(3,5)

In [29]:
score

array([[92, 61, 35, 56, 20],
       [72, 20, 16, 16, 74],
       [60, 77, 36, 87, 15]])

In [31]:
arr5 = np.array([11,22,33,0,55])
np.any(arr5)

True

In [ ]:
arr5 = np.